services:
  db:
    image: postgres:latest
    container_name: postgres
    profiles:
      - local
      - compose
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:latest
    container_name: redis
    profiles:
      - local
      - compose
    ports:
      - "${REDIS_PORT}:6379"

  app:
    image: mark3317/webchat-backend:latest
    container_name: backend
    profiles:
      - compose
    depends_on:
      - redis
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - FRONT_URL=${FRONT_URL}
    ports:
      - "${APP_PORT}:8080"