server:
  servlet:
    context-path: /api

spring:
  application:
    name: webchat-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  docker:
    compose:
      profiles:
        active: local
  flyway:
    baseline-on-migrate: true

jwt:
  lifetime: 30m
  secret: 219A8DE52BC049D10CD2F9C6669B33F66BC8A455626652A518C53176E5A02B91