server:
  port: 8082
  servlet:
    context-path: /WebChat/api

spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  application:
    name: WebChat
#  data:
#    redis:
#      database: 0
#      host: localhost
#      port: 6379
#  datasource:
#    username: webchat
#    password: webchat
#    url: jdbc:postgresql://localhost:5432/webchat
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


jwt:
  lifetime: 30m
  secret: 219A8DE52BC049D10CD2F9C6669B33F66BC8A455626652A518C53176E5A02B91