server:
  port: 8081
  servlet:
    context-path: /WebChat/api

spring:
  docker:
    compose:
      stop:
        command: down
  application:
    name: WebChat
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: always

jwt:
  lifetime: 30m
  secret: 219A8DE52BC049D10CD2F9C6669B33F66BC8A455626652A518C53176E5A02B91